export const technicServiceStatusTypes = [
  { value: 0, text: "İade" },
  { value: 1, text: "Bekliyor" },
  { value: 2, text: "Parça Bekleniyor" },
  { value: 3, text: "Tamir Ediliyor" },
  { value: 4, text: "Hazır" },
  { value: 5, text: "Teslim Edildi" },
];

export const warrantyDurations = [
  { value: 0, text: "Garanti Yok" },
  { value: 7, text: "1 Hafta" },
  { value: 14, text: "2 Hafta" },
  { value: 30, text: "1 Ay" },
  { value: 60, text: "2 Ay" },
  { value: 90, text: "3 Ay" },
  { value: 120, text: "4 Ay" },
  { value: 150, text: "5 Ay" },
  { value: 180, text: "6 Ay" },
  { value: 210, text: "7 Ay" },
  { value: 240, text: "8 Ay" },
  { value: 270, text: "9 Ay" },
  { value: 300, text: "10 Ay" },
  { value: 330, text: "11 Ay" },
  { value: 365, text: "1 Yıl" },
  { value: 365 * 2, text: "2 Yıl" },
  { value: 365 * 3, text: "3 Yıl" },
  { value: 365 * 4, text: "4 Yıl" },
  { value: 365 * 5, text: "5 Yıl" },
];
